services:
  dashboard:
    container_name: canvas_dashboard
    image: python:3.12-alpine
    build:
      dockerfile: Dockerfile
    ports:
      - "5101:5101"
    environment:
      - DB_HOST=database
      - DB_USER=innovation
      - DB_PASSWORD=admin
      - DB_NAME=canvas_dashboard
      - KEYCLOAK_SERVER_URL=keycloak_url
      - KEYCLOAK_CLIENT_ID=keycloak_client_id
      - KEYCLOAK_REALM=keycloak_realm
      - KEYCLOAK_CLIENT_SECRET=keycloak_client_secret
      - CANVAS_API_KEY=canvas_api_key
    volumes:
      - ./courses:/src/courses
    networks:
      - dashboard-network
  database:
    image: "postgres:14.7-alpine"
    environment:
        - POSTGRES_USER=innovation
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=canvas_dashboard
        - POSTGRES_PORT=5432
    ports:
      - "25432:5432"
    volumes:
      - dashboard-database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - dashboard-network
volumes:
  courses:
  dashboard-database-data:
networks:
    dashboard-network: