DIR_DIV = "/"
ENVIRONMENT_PATH = ".." + DIR_DIV + "environment" + DIR_DIV
ENVIRONMENT_FILE_NAME = ENVIRONMENT_PATH + "environment.json"
WORKFLOW_FILE_NAME = ENVIRONMENT_PATH + "workflow.json"
SECRET_API_KEY_FILE_NAME = ENVIRONMENT_PATH + "canvas_api_key.json"
MSTEAMS_API_KEY_FILE_NAME = ENVIRONMENT_PATH + "msteams_api.json"